### ISSUE TITLE
eth_sendBundle json parse error

### ISSUE THREAD

**Issue by bgelb** [Taichi-Network/docs#16]
Hello -

I use https://relay.flashbots.net and https://mev-relay.ethermine.org for my application.

I tried to add https://api.taichi.network:10001/rpc/public and use the eth_sendBundle RPC, but I always get this error message:

{'error': {'code': -32600, 'message': 'invalid json request'}}

The exact same RPC is also sent to flashbots and ethermine relays and it is accepted correctly. Does taichi eth_sendBundle have any special requirements that are different from flashbots spec? I would like to be able to submit bundles direct to taichi.

Many thanks,
Ben

**Comment by ljm625** [comment]
same issue here

**Comment by wsy2220** [comment]
Thanks for your report. We are investigating.

**Comment by wsy2220** [comment]
This error message occur when our nodes are overloaded. Just retry a few seconds later should be ok. 

`eth_sendBundle` is resource heavy, this is hard to avoid.

**Comment by bgelb** [comment]
I don't believe this is an accurate diagnosis. I've tried it many times. It never works.

**Comment by wsy2220** [comment]
Can you share your detailed failed request?

**Comment by ljm625** [comment]
overload make sense for me, I tried before and it works. Just tried and works too seems.

**Comment by bgelb** [comment]
I checked it again.

I am now seeing a different behavior.

RPC no longer returns with an error (good).

But it returns 'result' field 'None'. Is this expected?

I see:
{'jsonrpc': '2.0', 'id': 1, 'result': None}

I would expect:
{'jsonrpc': '2.0', 'id': 1, 'result': {'bundleHash': '0x...'}}

Can you clarify the expected result from your RPC implementation? Maybe it is different than flashbots spec?

**Comment by wsy2220** [comment]
`{ "jsonrpc": "2.0",    "id": 1,    "result": null }`  is the expected return from mev-geth, see https://github.com/flashbots/mev-geth/blob/v1.10.8-mev0.3.0/eth/api_backend.go#L237

`bundleHash` is added by flashbots relay, which we don't use.

**Comment by bgelb** [comment]
Thank you for the clarification. I think it is working now.

You may wish to remove the link to https://docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint from https://taichi.network/, since behavior of your endpoint is different from flashbots spec.

Thank you for your help!
