### ISSUE TITLE
Could not fetch chain ID.

### ISSUE THREAD

**Issue by rainwater11** [Taichi-Network/docs#17]
When adding the network to MetaMask, it says "Could not fetch chain ID" and doesn't let me proceed. The chain ID that I put is 1.

**Comment by wsy2220** [comment]
We have stopped service since Ooc.15. Sorry.

**Comment by rainwater11** [comment]
Ok I understand. What can I use as an alternative?

**Comment by wsy2220** [comment]
Well, I don't know direct replacement yet.
