### ISSUE TITLE
eth_sendRawTransactions has limit of 20

### ISSUE THREAD

**Issue by wjmelements** [Taichi-Network/docs#6]
We request you increase this limit to 30.

Also I cannot find the documentation for this rpc anymore.

**Comment by wjmelements** [comment]
Also according to our own documentation I believe the limit used to be 1000.

**Comment by wjmelements** [comment]
Please restore the [prior documentation of this method](https://github.com/Taichi-Network/docs/blob/81eb5cb891480653b374bd5973bde8f80175dcc6/api_en.md#eth_sendrawtransactions)

**Comment by wsy2220** [comment]
Hi, `eth_sendRawTransactions` is deprecated. We recommend using jsonrpc standard's batch mode. 

https://www.jsonrpc.org/specification#batch

```
--> [
        {"jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params": ["0xaaaaaaaaaaaaaaaaaaaaa"], "id": "1"},
        {"jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params": ["0xbbbbbbbbbbbbbbbbbbbbb"], "id": "2"}
    ]
<-- [
        {"jsonrpc": "2.0", "result": "0xaaa", "id": "1"},
        {"jsonrpc": "2.0", "result": "0xbbb", "id": "2"}
    ]
```

**Comment by wjmelements** [comment]
That is what we did before, and you asked us to use your method. We can now
delete the code we wrote for you. Thanks for supporting batch jsonrpc. You
can close this issue.
