### ISSUE TITLE
Tachi Network & Flashbots

### ISSUE THREAD

**Issue by apiscerena** [Taichi-Network/docs#8]
我有两个问题想问一下：

1. 发送隐私交易是不是仅需把原来的RPC URL 换成  const web3 = new Web3(“https://api.taichi.network:10001/rpc/private”)就可以了？内部代码还需要更改吗？
2. 如果我用Tachi的 https://api.taichi.network:10001/rpc/private, 发送交易，是不是可以避免被Flashbots恶意抢跑呢？

**Comment by wsy2220** [comment]
1. yes
2. yes

**Comment by apiscerena** [comment]
我试了一下，在代码里仅是直接换的const web3 = new Web3(“https://api.taichi.network:10001/rpc/private”)，可以发送隐私交易，但web3  contract.methods.function().send() 后获取不到 receipt是为什么呀？直接显示Error: Failed to check for transaction receipt，是不是里面代码也要改呀？ @wsy2220

**Comment by wsy2220** [comment]
交易上链以后才会有receipt

**Comment by Trickle-dev** [comment]
@wsy2220 is it possible to set up a group on Telegram? Would like to discuss proposal with you

**Comment by wsy2220** [comment]
> @wsy2220 is it possible to set up a group on Telegram? Would like to discuss proposal with you

Can you make it clear what type of proposal you want to discuss?

**Comment by Trickle-dev** [comment]
> 
> Can you make it clear what type of proposal you want to discuss?

Would first like to gauge if private transactions are suitable for adding liquidity pairs on Uniswap. 
We would like to provide potential funding.

**Comment by apiscerena** [comment]
> Would first like to gauge if private transactions are suitable for adding liquidity pairs on Uniswap.



> 交易上链以后才会有receipt

这个我明白了，谢谢。之前注意到spark pool也激活了 MEV flashbots，这会不会意味着一些profits searcher bots仍然可以看到spark mempool里的交易，并对其进行攻击呢？还是说这些bots只能在公共的mempool里，而spark mempool是不对他们开放的？

**Comment by wsy2220** [comment]
> 这个我明白了，谢谢。之前注意到spark pool也激活了 MEV flashbots，这会不会意味着一些profits searcher bots仍然可以看到spark mempool里的交易，并对其进行攻击呢？还是说这些bots只能在公共的mempool里，而spark mempool是不对他们开放的？

隐私交易的mempool是独立的，不会被其他人看到。这些bots只能看到公共mempool

**Comment by teluns** [comment]
隐私交易是不是比普通交易慢很多呢？
